<?xml version="1.0" encoding="UTF-8"?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5">
	<global_window_position top="27" left="76" height="647" width="844"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="zorcanda!.20050427192852" a="E"><vh>@thin SVNIntegrator.py</vh></v>
</vnodes>
<tnodes>
</tnodes>
</leo_file>
